[package]
name = "ex_pbkdf2"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ex_pbkdf2"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23"
pbkdf2 = "0.10"
rand_core = { version = "0.6", features = ["std"] }
