[package]
name = "ex_pbkdf2"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ex_pbkdf2"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27"
pbkdf2 = { version = "0.12", features = ["simple"] }
rand_core = { version = "0.6", features = ["std"] }
